[server]
host = "0.0.0.0"
port = 5000
debug = false
token = "changeme!"
# ensure last slash and full or relative path, not with env variables
music_folder = "/home/user/Music/"
# can be just a / and ensure last slash
base_url = '/'


[keyboard]
togglePlay = "t"
playNextSong = "n"
playPrevSong = "p"
next10sec = "ArrowRight"
prev10sec = "ArrowLeft"
volumeUp = "ArrowUp"
volumeDown = "ArrowDown"
toggleMute = "m"
toggleLoop = "l"
changeQueue = "q"
changeSpeedUp = ">"
changeSpeedDown = "<"
toggleFullscreen = "f"
toggleDetach = "d"
toggleRemote = "r"
